
// This file was auto-generated by ML.NET Model Builder. 

using MLModel_ConsoleApp1;
using System.IO;

public class MlAnalis
{
    private static void Main(string[] args)
    {
        string path = @"C:\Users\Bolofficial\Desktop\РАКИ\akiec\ISIC_0024329.jpg";
        Analise(path);
    }

    public static Dictionary<string,float> Analise(string puth) 
    {
        var imageBytes = File.ReadAllBytes(puth);
        MLModel.ModelInput sampleData = new MLModel.ModelInput()
        {
            ImageSource = imageBytes,
        };
        var sortedScoresWithLabel = MLModel.PredictAllLabels(sampleData);
        var result = new Dictionary<string, float>();
        foreach (var label in sortedScoresWithLabel) 
        {
            result.Add(label.Key, label.Value);
        }
        return result;
    }
}